seed: 711
method: baseline
dataset: mnist
subset_size: 1000
curv: ggn
n_epochs: 500
model: mininet
lr: 1e-3
lr_min: 1e-9
lr_hyp: 1e-1
lr_hyp_min: 1e-2
n_epochs_burnin: 10
batch_size: 250
marglik_batch_size: 1000
marglik_frequency: 5
n_hypersteps_prior: 10
download_data: False