seed: 711
method: lila
n_samples_aug: 30
dataset: mnist_r180
subset_size: 1000
curv: ggn
n_epochs: 500
model: mininet
lr: 1e-3
lr_min: 1e-9
lr_hyp: 1e-1
lr_hyp_min: 1e-2
lr_aug: 0.05
lr_aug_min: 0.005
n_epochs_burnin: 10
batch_size: 250
marglik_batch_size: 1000
partial_batch_size: 500
marglik_frequency: 1
n_hypersteps_prior: 2
n_hypersteps: 2
download_data: False