seed: 1
method: lila
n_samples_aug: 30
dataset: mnist_r180
subset_size: 1000
curv: ggn
n_epochs: 5
model: mininet
lr: 1e-3
lr_min: 1e-3
lr_hyp: 1e-1
lr_hyp_min: 1e-3
lr_aug: 0.005
lr_aug_min: 0.005
n_epochs_burnin: 0
batch_size: 1000
marglik_batch_size: 1000
partial_batch_size: 1000
marglik_frequency: 1
n_hypersteps_prior: 1
n_hypersteps: 1
download_data: False
