seed: 711
method: lila
n_samples_aug: 20
dataset: cifar10
subset_size: 50000
model: wrn
batch_size: 128
curv: ggn
n_epochs: 200
lr: 1e-1
lr_min: 1e-6
lr_hyp: 1e-1
lr_hyp_min: 1e-1
lr_aug: 0.05
lr_aug_min: 0.005
n_epochs_burnin: 10
marglik_batch_size: 120
partial_batch_size: 40
marglik_frequency: 1
n_hypersteps_prior: 4
n_hypersteps: 140
bound: False
download_data: False
grouped_loader: False
single_output: False
independent_outputs: False
kron_jac: True