seed: 711
method: lila
dataset: tinyimagenet
subset_size: 100000
n_samples_aug: 10
curv: ggn
n_epochs: 100
lr: 1e-1
lr_min: 1e-6
lr_hyp: 1e-1
lr_hyp_min: 1e-1
lr_aug: 1e-2
lr_aug_min: 1e-3
n_epochs_burnin: 10
batch_size: 128
marglik_batch_size: 70
marglik_frequency: 1
n_hypersteps_prior: 4
n_hypersteps: 50
bound: True
single_output: True
single_output_iid: True
independent_outputs: True
kron_jac: True
grouped_loader: False
prior_prec_init: 25.0
download_data: False
model: resnet
