seed: 711
method: baseline
dataset: tinyimagenet
subset_size: 100000
curv: ggn
n_epochs: 100
lr: 1e-1
lr_min: 1e-6
lr_hyp: 1e-1
lr_hyp_min: 1e-1
n_epochs_burnin: 10
batch_size: 128
marglik_batch_size: 400
marglik_frequency: 5
n_hypersteps_prior: 50
prior_prec_init: 25.0
download_data: False
model: resnet
